name: nix-flake-check

on:
  push:
    tags:
      - "v*"
    paths:
      - "**.nix"
      - "flake.lock"
      - "src/**"
      - ".github/workflows/nix.yml"
  pull_request:
    paths:
      - "**.nix"
      - "flake.lock"
      - "src/**"
      - ".github/workflows/nix.yml"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21
      - name: Nix flake check
        run: nix flake check
      - name: Build package
        run: nix build .#
      - name: Run CLI (version check)
        run: ./result/bin/pomodoro --version
